services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0 
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${COMPOSE_PROJECT_NAME}db
      - MYSQL_USER=${COMPOSE_PROJECT_NAME}
      - MYSQL_PASSWORD=${COMPOSE_PROJECT_NAME}
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      isolated-nw:
        aliases:
        - mysql
    command: 
        - "--innodb_use_native_aio=0"

volumes:
  dbdata: 